trigger: 
 - master

pool:
   vmImage: 'windows-2019'

steps: 
- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  inputs:
    command: 'build'
    arguments: '-a -v github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1 github.com/Microsoft/hcsshim/cmd/runhcs'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop