trigger: 
 - master

pool:
   vmImage: 'windows-2019'

steps: 
- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  inputs:
    command: 'build'
    arguments: '-a -v -o $(Build.ArtifactStagingDirectory) github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    arguments: '-a -v -o $(Build.ArtifactStagingDirectory) github.com/Microsoft/hcsshim/cmd/runhcs'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'test'
    arguments: '-o $(Build.ArtifactStagingDirectory) -c github.com/Microsoft/hcsshim/test/cri-containerd --tags functional'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop