name: hcsshim test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    shell: powershell

jobs:

  build:
    name: HCSShim tests
    runs-on: windows-latest
    steps:
      - name: Test
        run: |
          cd test
          echo $Env:Path
          echo $Env:GOPATH
          $Env:Path += ";$ENV:GOPATH\bin"
          echo $Env:Path
          dir $Env:GOPATH\bin

    
